name: LinuxServer-Bazarr
services:
  app:
    image: hotio/bazarr:nightly
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
      volumes:
        - container: /config
          description:
            en_us: Appdata
        - container: /movies
          description:
            en_us: Movies
        - container: /tv
          description:
            en_us: TV
      ports:
        - container: '6767'
          description:
            en_us: 'Container Port: 6767'
    ports:
      - target: 6767
        published: 6767
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/bazarr/config
        target: /config
      - type: bind
        source: /DATA/Media/Movies
        target: /movies
      - type: bind
        source: /DATA/Media/TV Shows
        target: /tv
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: 'Visit homepage: https://www.bazarr.media'
  tagline:
    en_us: A Companion Application To Sonarr And Radarr. It Can Manage And Download Subtitles Based On Your Requirements. You Define Your Preferences By Tv Show Or Movie And Bazarr Takes Care Of Everything For You.
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/bazarr.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/bazarr.png
  title:
    en_us: Bazarr
  category: Media
  port_map: '6767'
